apiVersion: v1
kind: Pod
metadata:
  name: testpmd
#  annotations:
#    k8s.v1.cni.cncf.io/networks: sriov-dpdk-net2000

spec:
  containers:
  - name: testpmd
    image: <DPDK testpmd image>
    securityContext:
        privileged: true
    resources:
      requests:
        intel.com/intel_x710vfio: "2"
        memory: 1000Mi
        hugepages-1Gi: 2Gi
        cpu: '1'
      limits:
        intel.com/intel_x710vfio: "2"
        hugepages-1Gi: 2Gi
        cpu: '1'
        memory: 2000Mi
    volumeMounts:
      - mountPath: /dev/hugepages
        name: hugepage
        readOnly: False
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
